// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXuu0gEeY0LvwLsF_Q4euJdk5WOvAFurA',
    appId: '1:902598739687:web:aa914611b45885117e0442',
    messagingSenderId: '902598739687',
    projectId: 'flux-store-caca1',
    authDomain: 'flux-store-caca1.firebaseapp.com',
    storageBucket: 'flux-store-caca1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6xSjSERmKmTpl9kwgz3sufaPpbW3xSUc',
    appId: '1:902598739687:android:182240544c35146a7e0442',
    messagingSenderId: '902598739687',
    projectId: 'flux-store-caca1',
    storageBucket: 'flux-store-caca1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXuu0gEeY0LvwLsF_Q4euJdk5WOvAFurA',
    appId: '1:902598739687:web:2302f7442bb953a97e0442',
    messagingSenderId: '902598739687',
    projectId: 'flux-store-caca1',
    authDomain: 'flux-store-caca1.firebaseapp.com',
    storageBucket: 'flux-store-caca1.firebasestorage.app',
  );
}
